const techOptions = {
  developmentTechnologies: [
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "Ruby",
    "Ruby on Rails",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "PHP",
    "Laravel",
    "HTML",
    "CSS",
    "Sass",
    "Less",
    "TypeScript",
    "SQL",
    "NoSQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "GitHub",
    "GitLab",
    "JIRA",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "Firebase",
    "RESTful APIs",
    "GraphQL",
    "Webpack",
    "Babel",
    "Jenkins",
    "Travis CI",
    "Redux",
    "MobX",
    "Flask",
    "ASP.NET",
    "Symfony",
    "RubyMine",
    "Visual Studio Code",
    "Sublime Text",
    "Eclipse",
    "IntelliJ IDEA",
    "Xcode",
  ],

  infraDevopTechnologies: [
    "Docker",
    "Kubernetes",
    "Ansible",
    "Terraform",
    "AWS",
    "Amazon EC2",
    "Amazon S3",
    "Amazon RDS",
    "Amazon VPC",
    "Azure",
    "Azure Virtual Machines",
    "Azure Blob Storage",
    "Azure Kubernetes Service (AKS)",
    "Google Cloud Platform (GCP)",
    "Google Compute Engine",
    "Google Kubernetes Engine (GKE)",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitLab CI/CD",
    "GitHub Actions",
    "Prometheus",
    "Grafana",
    "ELK Stack (Elasticsearch, Logstash, Kibana)",
    "Nagios",
    "Zabbix",
    "IaC (Infrastructure as Code)",
    "Continuous Integration (CI)",
    "Continuous Deployment (CD)",
    "Serverless Computing",
    "Load Balancers",
    "NGINX",
    "Apache HTTP Server",
    "HAProxy",
    "Configuration Management",
    "Puppet",
    "Chef",
    "SaltStack",
    "Monitoring and Alerting",
    "New Relic",
    "Datadog",
    "Splunk",
    "Infrastructure Security",
    "Firewalls",
    "VPN (Virtual Private Network)",
    "IDS/IPS (Intrusion Detection System/Intrusion Prevention System)",
    "Cloud Security Groups",
    "Identity and Access Management (IAM)",
    "DevSecOps (DevOps + Security)",
    "CICD Pipelines",
    "Container Orchestration",
    "Microservices Architecture",
  ],
  testingTechnologies: [
    "Selenium",
    "Cypress",
    "JUnit",
    "TestNG",
    "JUnit 5",
    "TestCafe",
    "Protractor",
    "Appium",
    "JUnit Jupiter",
    "Jest",
    "Mocha",
    "Chai",
    "Cucumber",
    "RSpec",
    "Postman",
    "SoapUI",
    "LoadRunner",
    "Jira",
    "TestRail",
    "TestLink",
    "Zephyr",
    "Squash TM",
    "Test Management Tools",
    "Test Automation Frameworks",
    "Continuous Testing",
    "Code Review Tools",
    "Static Analysis Tools",
    "Performance Testing Tools",
    "Security Testing Tools",
    "Mutation Testing Tools",
    "Exploratory Testing",
    "Test Data Management Tools",
    "Test Environment Management Tools",
    "API Testing Tools",
    "Web Testing Tools",
    "Mobile App Testing Tools",
    "Browser DevTools",
    "Cross-Browser Testing Tools",
    "Test Driven Development (TDD)",
    "Behavior Driven Development (BDD)",
    "Load Testing Tools",
    "Load Balancer Testing Tools",
    "Accessibility Testing Tools",
    "Code Coverage Tools",
    "Test Reporting and Analytics Tools",
    "Test Automation Scripts and Libraries",
  ],
};

export default techOptions;
